services:
  api_gateway:
    container_name: api_gateway
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - api
      - external
    volumes:
      - ./gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - inventory
      - app_client

  db_service:
    container_name: db_service
    build:
      context: ./services/servicio-db
      dockerfile: ../Dockerfile
    networks:
      - api
      - external

  inventory:
    build:
      context: ./services/servicio-inventario
      dockerfile: ../Dockerfile
    networks:
      - api
    depends_on:
      - db_service
    deploy:
      mode: replicated
      replicas: 3

  app_client:
    container_name: app_client
    build:
      context: ./services/app-client
      dockerfile: ../Dockerfile
    ports:
      - 8082:5000
    depends_on:
      - db_service
    networks:
      - external
    environment:
      - REQUESTS_TO_SEND=300
      - INTERVAL=0.4

networks:
  api:
  external:
