services:
  api_gateway:
    container_name: api_gateway
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - api
      - external
    volumes:
      - ./gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - inventory
      - app_client

  inventory:
    build:
      context: ./services/inventory
      dockerfile: ../Dockerfile
    volumes:
      - ./services/inventory/:/app
    networks:
      - api
    # deploy:
    #   mode: replicated
    #   replicas: 3
    depends_on:
      - validator

  validator:
    build:
      context: ./services/validator
      dockerfile: ../Dockerfile
    volumes:
      - ./services/validator/:/app
    networks:
      - api

  app_client:
    container_name: app_client
    build:
      context: ./services/client
      dockerfile: ../Dockerfile
    ports:
      - 8082:5000
    volumes:
      - ./services/client/:/app
    networks:
      - external
    environment:
      - REQUESTS_TO_SEND=300
      - INTERVAL=0.4

networks:
  api:
  external:
